# -*- coding: utf-8 -*-
"""ML_Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OT9vii0TeIf7jX45WlzeKOGKuWeGvYqu

#Drive Access
"""

from google.colab import drive
drive.mount('/content/drive/')

"""# Importing libraries"""

import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

"""# Importing the dataset"""

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Bootcamp/Deployment of ML/Housing.csv')

df.head()

df.tail()

df.shape

df.info()

df.isnull().sum()

df.describe()

df.columns

columns1 =  ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea','furnishingstatus']
def convert(x):
    return x.map({'yes':1 , 'no':0 , 'unfurnished':0 , 'semi-furnished':1 , 'furnished':2 })
df[columns1] = df[columns1].apply(convert)
df

sns.pairplot(df)
plt.show()

sns.heatmap(df.corr(), annot=True, cmap='Greens')

model = LinearRegression()

X = ['area','bedrooms','bathrooms','stories','mainroad','guestroom','	basement','hotwaterheating','airconditioning','parking','prefarea','furnishingstatus']
y = ['price']

X

y

df_train, df_test = train_test_split(df,train_size=0.8,test_size=0.2)

y_train = df_train.pop('price')
X_train = df_train
y_test = df_test.pop('price')
X_test = df_test

len(X_train)

len(X_test)

len(y_train)

len(y_test)

model.fit(X_train, y_train)

model.intercept_

model.coef_

y_pred = model.predict(X_test)

r2_score(y_test, y_pred)